#!/bin/sh
# Prepare a fresh clone. Idempotent — safe to re-run at any time.
#
# Generated by development-guidelines/setup.swift, and tracked on purpose:
# the framework directory is gitignored, so it is not in a fresh clone and
# cannot be what you run first.

set -eu
cd "$(git rev-parse --show-toplevel)"

# .githooks/ is tracked; core.hooksPath is per-clone git config and cannot be
# committed. Git refuses to let a repository configure its own hook path, so
# this line is the one thing a clone genuinely cannot do for itself.
git config core.hooksPath .githooks
echo "✓ core.hooksPath = .githooks"

# What the hooks need in order to be worth having.
warnings=0

if ! command -v swift >/dev/null 2>&1; then
  echo "✗ swift is not on PATH — the hooks build before checking, so they will fail" >&2
  warnings=$((warnings + 1))
fi

if ! command -v quality-gate >/dev/null 2>&1; then
  echo "✗ quality-gate is not on PATH" >&2
  echo "  Where the hooks are a project's only automatic gate they refuse to run" >&2
  echo "  without it, rather than passing silently. Install it:" >&2
  echo "    git clone https://github.com/jpurnell/quality-gate-swift.git ~/.quality-gate-swift" >&2
  echo "    cd ~/.quality-gate-swift && ./scripts/install.sh" >&2
  warnings=$((warnings + 1))
fi

if [ "$warnings" -eq 0 ]; then
  echo "✓ swift and quality-gate found"
  echo ""
  echo "Ready. The hooks will run on your next commit."
else
  echo ""
  echo "Hooks are wired up, but $warnings prerequisite(s) are missing above."
fi
